name: FelpFit

options:
  minimumXcodeGenVersion: 2.40.0
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0

targets:
  FelpFit:
    type: application
    platform: iOS
    sources:
      - path: FelpFit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.felpfit.ios
        PRODUCT_NAME: FelpFit
        INFOPLIST_FILE: FelpFit/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: 1.5.0
        CURRENT_PROJECT_VERSION: 146
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      gatherCoverageData: false
